"""
test_model.py
=============
Evaluates a saved TheoryDenoiserNet checkpoint on SAT-consistent theories
generated by reusing `generate_consistent_theory` from `main.py`.

For each theory, three metrics are reported:

  1. Revision steps
       Number of clauses removed that would otherwise make the theory
       trivially consistent (all-zero / empty) during iterative denoising.
       Guards against the degenerate solution of zeroing out everything.

  2. Denoising steps to first consistent theory
       The reverse diffusion loop stops as soon as a SAT-consistent
       prediction is found.
       Reports the normalized percentage of steps used relative to the
       randomized starting noise level.

  3. Consistency rate
       Percentage of all test theories that reached a consistent prediction
       within the allowed steps.

Usage
-----
    python test_model.py --checkpoint outputs/theory_denoiser_<run_id>.pt

The checkpoint path can also be set via CHECKPOINT_PATH below.
"""

import argparse
import sys
from pathlib import Path
from statistics import mean, stdev
from collections import Counter

import torch

# ── import everything from the training module ────────────────────────────────
sys.path.insert(0, str(Path(__file__).parent))
from main import D3PMForwardCorruption, TheoryDenoiserNet, is_consistent

# ==========================================
# Logging Setup
# ==========================================
log_lines: list[str] = []

def emit(msg: str = "") -> None:
    """Prints to console and saves to an in-memory list for file writing."""
    print(msg)
    log_lines.append(msg)


# ── default checkpoint (override with --checkpoint) ───────────────────────────
CHECKPOINT_PATH: str | None = None   # e.g. "outputs/theory_denoiser_20260314_120000.pt"

# ==========================================
# Test Evaluation Configuration
# ==========================================
START_DENOISE_TRAJ_PCT_MIN = 0.3  # Minimum trajectory progress to start denoising from (30%)
START_DENOISE_TRAJ_PCT_MAX = 0.8  # Maximum trajectory progress to start denoising from (80%)


def _extract_theory_from_offline_entry(entry: dict) -> torch.Tensor:
    """Extract corrupted state from offline dataset entry."""
    if "corrupted" in entry:
        source = entry["corrupted"]
    elif "trajectory" in entry and isinstance(entry["trajectory"], torch.Tensor) and entry["trajectory"].ndim == 3:
        source = entry["trajectory"][-1]
    else:
        source = entry["clean"]

    original_m = int(entry.get("original_m", source.size(1)))
    original_m = max(1, min(original_m, source.size(1)))
    return source[:, :original_m].clone().long()


def _sample_trajectory_start(entry: dict, num_timesteps: int, min_pct: float, max_pct: float) -> int:
    """Sample a start timestep based on trajectory progress within [min_pct, max_pct] range."""
    traj = entry.get("trajectory", None)
    
    if isinstance(traj, torch.Tensor) and traj.ndim == 3 and traj.size(0) > 1:
        max_idx = traj.size(0) - 1
        sampled_pct = min_pct + torch.rand(1).item() * (max_pct - min_pct)
        idx_t = int(round(sampled_pct * max_idx))
        idx_t = max(1, min(max_idx, idx_t))
        progress = idx_t / max(1, max_idx)
    else:
        progress = max_pct
    
    mapped_t = int(round(progress * (num_timesteps - 1)))
    start_t = max(1, min(num_timesteps - 1, mapped_t))
    return start_t


def find_default_test_dataset() -> Path | None:
    """Prefer outputs/test.pt, fallback to dataset/test.pt."""
    candidates = [Path("outputs") / "test.pt", Path("dataset") / "test.pt"]
    for path in candidates:
        if path.exists():
            return path
    return None


def load_test_theories_from_pt(
    test_pt_path: Path,
    num_timesteps: int,
    start_pct_min: float = None,
    start_pct_max: float = None,
    max_items: int | None = None
) -> list[tuple[torch.Tensor, int]]:
    """Load test theories from offline .pt and sample trajectory-based start_t."""
    if start_pct_min is None:
        start_pct_min = START_DENOISE_TRAJ_PCT_MIN
    if start_pct_max is None:
        start_pct_max = START_DENOISE_TRAJ_PCT_MAX

    entries = torch.load(test_pt_path, map_location="cpu", weights_only=False)
    if not isinstance(entries, list):
        raise ValueError(f"Expected list in {test_pt_path}, got {type(entries)}")

    if max_items is not None:
        entries = entries[:max_items]

    theories: list[tuple[torch.Tensor, int]] = []
    for entry in entries:
        theory = _extract_theory_from_offline_entry(entry)
        start_t = _sample_trajectory_start(entry, num_timesteps, start_pct_min, start_pct_max)
        theories.append((theory, start_t))
    return theories


# ==========================================
# Revision-step counter
# ==========================================

def count_revision_steps(original: torch.Tensor, denoised: torch.Tensor) -> dict:
    """
    Compare original and final (denoised) theory element-wise.

    Returns percentage-only metrics:
      - total_change_pct: percentage of cells that changed value
      - empty_change_pct: percentage-point change in empty (0) cells
                          from original to final
    """
    if original.dim() != 2 or denoised.dim() != 2:
        return {
            "total_change_pct": 0.0,
            "empty_change_pct": 0.0,
        }

    # Align shapes: compare over the min shared columns (handles variable M)
    min_m = min(original.size(1), denoised.size(1))
    orig = original[:, :min_m]
    deno = denoised[:, :min_m]

    total_cells = float(max(1, deno.numel()))

    changed_cells = float((orig != deno).sum().item())
    original_empty_cells = float((orig == 0).sum().item())
    final_empty_cells = float((deno == 0).sum().item())

    total_change_pct = 100.0 * changed_cells / total_cells
    empty_change_pct = 100.0 * (final_empty_cells - original_empty_cells) / total_cells

    return {
        "total_change_pct": total_change_pct,
        "empty_change_pct": empty_change_pct,
    }


# ==========================================
# Per-theory denoising evaluation
# ==========================================

def denoise_until_consistent(
    theory: torch.Tensor,
    model: TheoryDenoiserNet,
    corrupt: D3PMForwardCorruption,
    start_t: int,
    device: torch.device,
) -> dict:
    """
    Run the reverse diffusion loop on a SINGLE theory.

    Stops as soon as the predicted x_0 is SAT-consistent, or after
    `start_t` steps, whichever comes first.
    """
    model.eval()

    input_consistent = is_consistent(theory)

    N, M = theory.shape
    # Build clause mask: all columns active (no padding for single theory)
    clause_mask = torch.ones(1, M, dtype=torch.bool, device=device)

    # Batch-size-1 tensor: offline input is already the starting state for denoising
    x_t = theory.unsqueeze(0).to(device)               # (1, N, M)

    with torch.no_grad():
        # Capture the provided starting state to measure edits against it
        x_initial_cpu = x_t[0, :, clause_mask[0].cpu()].cpu().clone()

        steps_to_first = start_t
        reached_consistent = False
        final_theory = None
        x_0_pred = x_t  # fallback if loop body never executes

        # Only reverse from start_t down to 1
        for t_step in reversed(range(1, start_t + 1)):
            t_tensor = torch.full((1,), t_step, device=device, dtype=torch.long)
            logits = model(x_t, t_tensor, clause_mask=clause_mask)
            x_0_pred = logits.argmax(dim=-1)           # (1, N, M)

            # Check SAT consistency on the active (non-padded) columns
            pred_theory = x_0_pred[0].cpu()            # (N, M)
            active_theory = pred_theory[:, clause_mask[0].cpu()]

            if is_consistent(active_theory):
                reached_consistent = True
                steps_to_first = start_t - t_step + 1    # steps elapsed so far
                final_theory = active_theory
                break                                   # stop early

            if t_step > 1:
                t_minus_1 = torch.full((1,), t_step - 1, device=device, dtype=torch.long)
                x_t = corrupt.q_sample(x_0_pred, t_minus_1, clause_mask=clause_mask)
            else:
                x_t = x_0_pred

        if final_theory is None:
            final_theory = x_0_pred[0, :, clause_mask[0].cpu()].cpu()

        # Measure edits from the corrupted starting state
        rev = count_revision_steps(x_initial_cpu, final_theory)

    return {
        "input_consistent": input_consistent,
        "consistent": reached_consistent,
        "steps_to_first": steps_to_first,
        "total_change_pct": rev["total_change_pct"],
        "empty_change_pct": rev["empty_change_pct"],
        "final_theory": final_theory,
    }


# ==========================================
# Evaluation runner
# ==========================================

def run_evaluation(
    run_name: str,
    theories: list[tuple[torch.Tensor, int]],
    model: TheoryDenoiserNet,
    corrupt: D3PMForwardCorruption,
    device: torch.device,
) -> None:
    """
    Evaluate a list of theories and print a full summary.
    """

    def _summarize_theory_sizes(theory_list: list[tuple[torch.Tensor, int]]) -> dict:
        active_n_values = []
        active_m_values = []
        for item in theory_list:
            th = item[0]  # unpack the theory tensor from the tuple
            if th.dim() != 2:
                continue
            active_n = int((th != 0).any(dim=1).sum().item())
            active_m = int(th.size(1))
            active_n_values.append(active_n)
            active_m_values.append(active_m)

        def _stats(vals: list[int]) -> tuple[int, int, float, float]:
            if not vals:
                return 0, 0, 0.0, 0.0
            if len(vals) == 1:
                return min(vals), max(vals), float(vals[0]), 0.0
            return min(vals), max(vals), mean(vals), stdev(vals)

        n_min, n_max, n_mean, n_std = _stats(active_n_values)
        m_min, m_max, m_mean, m_std = _stats(active_m_values)
        n_dist = Counter(active_n_values)
        m_dist = Counter(active_m_values)

        return {
            "n_min": n_min,
            "n_max": n_max,
            "n_mean": n_mean,
            "n_std": n_std,
            "m_min": m_min,
            "m_max": m_max,
            "m_mean": m_mean,
            "m_std": m_std,
            "n_dist": n_dist,
            "m_dist": m_dist,
        }

    emit(f"\n{'=' * 60}")
    emit(f"  {run_name}")
    emit(f"  {len(theories)} theories  |  start_t: Randomized trajectory [{START_DENOISE_TRAJ_PCT_MIN:.1%}, {START_DENOISE_TRAJ_PCT_MAX:.1%}]")
    emit(f"{'=' * 60}")

    size_stats = _summarize_theory_sizes(theories)
    emit("  Theory size stats (realized in this test set):")
    emit(
        f"    Active N (non-empty rows): min={size_stats['n_min']}  max={size_stats['n_max']}  "
        f"mean={size_stats['n_mean']:.2f}  std={size_stats['n_std']:.2f}"
    )
    emit(
        f"    Active M (clauses):        min={size_stats['m_min']}  max={size_stats['m_max']}  "
        f"mean={size_stats['m_mean']:.2f}  std={size_stats['m_std']:.2f}"
    )

    n_dist_str = ", ".join(f"{k}:{v}" for k, v in sorted(size_stats["n_dist"].items()))
    m_dist_str = ", ".join(f"{k}:{v}" for k, v in sorted(size_stats["m_dist"].items()))
    emit(f"    Active N distribution: {n_dist_str}")
    emit(f"    Active M distribution: {m_dist_str}")

    all_consistent = []
    all_input_consistent = []
    all_steps = []
    all_start_t = []
    all_total_change_pct = []
    all_empty_change_pct = []

    for idx, (theory, start_t) in enumerate(theories):
        result = denoise_until_consistent(
            theory=theory,
            model=model,
            corrupt=corrupt,
            start_t=start_t,
            device=device,
        )
        all_consistent.append(result["consistent"])
        all_input_consistent.append(result["input_consistent"])
        all_steps.append(result["steps_to_first"])
        all_start_t.append(start_t)
        all_total_change_pct.append(result["total_change_pct"])
        all_empty_change_pct.append(result["empty_change_pct"])

        status = "OK" if result["consistent"] else "NO"
        input_status = "YES" if result["input_consistent"] else "NO"
        emit(
            f"  [{idx + 1:>4}] {status} "
            f"input_consistent={input_status:<3}  "
            f"steps={result['steps_to_first']:>3}/{start_t:<3}  "
            f"total_change={result['total_change_pct']:>6.2f}%  "
            f"empty_change={result['empty_change_pct']:>+7.2f}%"
        )

    # ── Summary ───────────────────────────────────────────────────────────────
    n_consistent = sum(all_consistent)
    consistency_rate = 100.0 * n_consistent / len(theories)

    # Filter steps and start times only for theories that reached consistency
    consistent_steps = [s for s, c in zip(all_steps, all_consistent) if c]
    consistent_starts = [t for t, c in zip(all_start_t, all_consistent) if c]

    avg_steps = mean(consistent_steps) if consistent_steps else float("nan")
    avg_start = mean(consistent_starts) if consistent_starts else float("nan")

    if consistent_steps:
        normalized_step_pcts = [(s / t) * 100.0 for s, t in zip(consistent_steps, consistent_starts)]
        avg_norm_pct = mean(normalized_step_pcts)
        std_norm_pct = stdev(normalized_step_pcts) if len(normalized_step_pcts) > 1 else 0.0
    else:
        avg_norm_pct, std_norm_pct = float("nan"), 0.0

    avg_total_change = mean(all_total_change_pct)
    std_total_change = stdev(all_total_change_pct) if len(all_total_change_pct) > 1 else 0.0
    avg_empty_change = mean(all_empty_change_pct)
    std_empty_change = stdev(all_empty_change_pct) if len(all_empty_change_pct) > 1 else 0.0

    emit(f"\n  -- Summary ---------------------------------------------")
    emit(f"  Metric 1 - Revision percentages (corrupted vs final)")
    emit(f"    Total change % : mean={avg_total_change:.2f}%  std={std_total_change:.2f}%")
    emit(f"    Empty change % : mean={avg_empty_change:+.2f}%  std={std_empty_change:.2f}%")
    emit(f"    (positive empty change => more empty cells in final output)")
    emit()
    emit(f"  Metric 2 – Denoising steps to first consistent theory")
    emit(f"    Evaluated on {n_consistent}/{len(theories)} theories that reached consistency")
    if consistent_steps:
        emit(f"    Absolute Steps: {avg_steps:.1f} steps (Average start_t was {avg_start:.1f})")
        emit(f"    Normalized    : Used {avg_norm_pct:.1f}% ± {std_norm_pct:.1f}% of allocated starting steps")
        emit(f"    (lower normalized % is better; model converged faster relative to its noise level)")
    else:
        emit(f"    No theories reached consistency.")
    emit()
    emit(f"  Metric 3 – Consistency rate")
    emit(f"    {n_consistent} / {len(theories)} = {consistency_rate:.1f}%")
    emit(f"    (higher is better)")
    emit(f"  Input consistency (before model denoising/corruption step)")
    emit(f"    {sum(all_input_consistent)} / {len(theories)} = {100.0 * sum(all_input_consistent) / len(theories):.1f}%")
    emit(f"{'=' * 60}")


# ==========================================
# Entry point
# ==========================================

def find_latest_checkpoint(output_dir: Path) -> Path | None:
    """Find the most recent checkpoint in the outputs directory."""
    checkpoints = sorted(output_dir.glob("theory_denoiser_*.pt"))
    return checkpoints[-1] if checkpoints else None


def main() -> None:
    parser = argparse.ArgumentParser(description="Evaluate a saved TheoryDenoiserNet checkpoint.")
    parser.add_argument(
        "--checkpoint",
        type=str,
        default=CHECKPOINT_PATH,
        help="Path to the .pt checkpoint file (default: latest in outputs/).",
    )
    parser.add_argument("--num_theories", type=int, default=500,
                        help="Number of test theories (default: 500).")
    parser.add_argument(
        "--test_pt",
        type=str,
        default=None,
        help="Path to offline test.pt (default: outputs/test.pt, then dataset/test.pt).",
    )
    args = parser.parse_args()

    # ── Locate checkpoint ─────────────────────────────────────────────────────
    ckpt_path = Path(args.checkpoint) if args.checkpoint else find_latest_checkpoint(Path("outputs"))
    if ckpt_path is None or not ckpt_path.exists():
        emit("ERROR: No checkpoint found. Run main.py first or pass --checkpoint <path>.")
        sys.exit(1)

    emit(f"Loading checkpoint: {ckpt_path}")
    ckpt = torch.load(ckpt_path, map_location="cpu", weights_only=False)
    cfg = ckpt["config"]

    N_base       = cfg["N_LITERALS"]
    M_base       = cfg["M_CLAUSES"]
    K           = cfg["K_STATES"]
    T           = cfg["NUM_TIMESTEPS"]

    # Use the largest N/M seen during curriculum training (fallback to base values).
    n_stages = cfg.get("CURRICULUM_N_LITERALS", [])
    m_stages = cfg.get("CURRICULUM_M_CLAUSES", cfg.get("CURRICULUM_STAGES", []))

    N = max([N_base] + [stage_n for _, stage_n in n_stages]) if n_stages else N_base
    M = max([M_base] + [stage_m for _, stage_m in m_stages]) if m_stages else M_base

    emit(
        f"Config from checkpoint: base N={N_base}  base M={M_base}  K={K}  T={T}"
    )
    emit(
        f"Evaluation sizes: max N={N}  max M={M}  start_t: randomized [50, 250]"
        f"Trajectory percent range: [{START_DENOISE_TRAJ_PCT_MIN:.1%}, {START_DENOISE_TRAJ_PCT_MAX:.1%}]  start_t approx: [{int(round(START_DENOISE_TRAJ_PCT_MIN * (T-1)))}, {int(round(START_DENOISE_TRAJ_PCT_MAX * (T-1)))}]"
    )

    device = torch.device("cpu")

    # ── Rebuild model and corruption process ──────────────────────────────────
    model = TheoryDenoiserNet(N=N, M=M, num_classes=K, num_timesteps=T)
    model.load_state_dict(ckpt["model_state_dict"])
    model.to(device)
    model.eval()

    corrupt = D3PMForwardCorruption(num_classes=K, num_timesteps=T)
    corrupt.to(device)

    test_pt_path = Path(args.test_pt) if args.test_pt else find_default_test_dataset()
    if test_pt_path is None or not test_pt_path.exists():
        emit("ERROR: No offline test dataset found. Pass --test_pt or create outputs/test.pt (or dataset/test.pt).")
        sys.exit(1)

    emit(f"\nLoading offline test theories from: {test_pt_path}")
    theories = load_test_theories_from_pt(
        test_pt_path,
        num_timesteps=T,
        start_pct_min=START_DENOISE_TRAJ_PCT_MIN,
        start_pct_max=START_DENOISE_TRAJ_PCT_MAX,
        max_items=args.num_theories
    )
    emit(f"Loaded {len(theories)} theories from offline dataset (with trajectory-sampled start_t)")

    # Run evaluation ONCE (prints to console and appends to log_lines automatically)
    run_evaluation(
        run_name="Evaluation – Offline test.pt (corrupted endpoint as input)",
        theories=theories,
        model=model,
        corrupt=corrupt,
        device=device,
    )

    # ── Save results ──────────────────────────────────────────────────────────
    from datetime import datetime
    run_id = datetime.now().strftime("%Y%m%d_%H%M%S")
    log_path = Path("outputs") / f"test_results_{run_id}.txt"
    log_path.parent.mkdir(parents=True, exist_ok=True)

    # Instantly dump memory to file
    log_path.write_text("\n".join(log_lines) + "\n", encoding="utf-8")

    # Standard print so the success message isn't logged inside the file itself
    print(f"\nResults saved to: {log_path}")


if __name__ == "__main__":
    main()